version: "3.9"

services: 
  # api calculator
  calculator-app:
    build: ./calculator
    container_name: "calculator_app"
    environment: 
      - APP_PORT=8080
      - MONGO_URL=mongodb://db:27017/calculator
    ports: 
      - "8080:8080"
    networks: 
      - app
    links: 
      - db

  # api tracker error
  tracker-error:
    build: ./tracker-error
    container_name: "tracker_error_app"
    environment: 
      - APP_PORT=8081
      - MONGO_URL=mongodb://db:27017/tracker
    ports: 
      - "8081:8081"
    networks: 
      - app
    depends_on: 
      - db

  # api simulator
  simulator:
    build: ./simulator
    container_name: "simulator_app"
    environment: 
      - APP_PORT=8082
    ports: 
      - "8082:8082"
    networks: 
      - app
    links: 
      - db

  # server mongodb
  db:
    image: mongo:4.4
    container_name: mongo-db
    ports:
    - "27017:27017"
    restart: "unless-stopped"
    networks:
      - app
      
networks: 
  app: